package processing.test.emisorandroid_nofunciona_;

/* autogenerated by Processing revision 1293 on 2023-10-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import oscP5.*;
import netP5.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class EmisorAndroid_NoFunciona_ extends PApplet {

/**
 * oscP5sendreceive by andreas schlegel
 * example shows how to send and receive osc messages.
 * oscP5 website at http://www.sojamo.de/oscP5
 */
 


  
OscP5 oscP5;
NetAddress myRemoteLocation;

public void setup() {
  /* size commented out by preprocessor */;
  frameRate(25);
  /* start oscP5, listening for incoming messages at port 12000 */
  oscP5 = new OscP5(this,12000);
  
  /* myRemoteLocation is a NetAddress. a NetAddress takes 2 parameters,
   * an ip address and a port number. myRemoteLocation is used as parameter in
   * oscP5.send() when sending osc packets to another computer, device, 
   * application. usage see below. for testing purposes the listening port
   * and the port of the remote location address are the same, hence you will
   * send messages back to this sketch.
   */
  myRemoteLocation = new NetAddress("192.168.1.110",9000);
}


public void draw() {
  background(0);  
}

public void mousePressed() {
  /* in the following different ways of creating osc messages are shown by example */
  OscMessage myMessage = new OscMessage("/test");
  OscMessage myMessage1 = new OscMessage("/mensaje1");
  
  myMessage.add(123); /* add an int to the osc message */
  myMessage1.add(1.2f);
  /* send the message */
  oscP5.send(myMessage, myRemoteLocation); 
  oscP5.send(myMessage1, myRemoteLocation); 
  println( "presionado" );
}


  public void settings() { size(400, 400); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "EmisorAndroid_NoFunciona_" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
